### ISSUE TITLE
Image.android.js Module Not found

### ISSUE THREAD

**Issue by iiitmahesh** [N3TC4T/Nearby-Live#3]
error: bundling: UnableToResolveError: Unable to resolve module `react/lib/ReactPropTypes` from `/Users/airbook/Documents/uw/test/Nearby-Live/node_modules/react-native/Libraries/Image/Image.android.js`: Module does not exist in the module map or in these directories

**Comment by N3TC4T** [comment]
https://github.com/facebook/react-native/issues/14596#issuecomment-310999291
